> **Before running the notebook:** Ensure that `WVS_Wave_7_Singapore_Csv_v5.1.csv` is located in the same directory as this notebook and that the `4002` Python kernel is selected. Then run all cells from top to bottom.

# 1. Import Libraries
This section imports the Python libraries required for data cleaning, analysis, visualisation, statistical modelling, and ANOVA.

In [1]:
import pandas as pd
import numpy as np
from plotnine import *
import warnings
warnings.filterwarnings('ignore')
import statsmodels.formula.api as smf
from statsmodels.stats.anova import anova_lm

## 2. Data Import

The WVS Wave 7 Singapore dataset is imported as a pandas DataFrame. The semicolon delimiter is specified to correctly separate the variables.

In [2]:
df = pd.read_csv("WVS_Wave_7_Singapore_Csv_v5.1.csv", sep=";")

# Check the number of rows and columns in the dataset
df.shape

### 2.1 Dataset Dimensions

The shape of the DataFrame is checked to identify the number of observations and variables in the dataset.

In [3]:
df.shape

(2012, 387)

### 2.2 Initial Data Inspection

The first five rows of the dataset are displayed to examine the structure and contents of the imported data.

In [4]:
df.head()

,version,doi,A_YEAR,B_COUNTRY,B_COUNTRY_ALPHA,C_COW_NUM,C_COW_ALPHA,D_INTERVIEW,FW_START,FW_END,...,WEIGHT4A,WEIGHT4B,RESEMAVALBWGT,RESEMAVALWGT,SECVALBWGT,Y001_1,Y001_2,Y001_3,Y001_4,Y001_5
6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070001.0,201911.0,202003.0,21.11,...,1.0,1.0,1.0,0.83,0.0,0.0,0.0,1.0,0.0,NaN
6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070002.0,201911.0,202003.0,17.34,...,1.0,1.0,1.0,0.83,1.0,1.0,1.0,0.0,1.0,NaN
6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070003.0,201911.0,202003.0,12.44,...,1.0,1.0,1.0,1.00,1.0,0.0,1.0,0.0,1.0,NaN
6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070004.0,201911.0,202003.0,14.02,...,1.0,1.0,1.0,1.00,1.0,0.0,0.0,0.0,0.0,NaN
6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070005.0,201911.0,202003.0,17.09,...,1.0,1.0,1.0,1.00,0.0,0.0,0.0,0.0,0.0,NaN

### 2.3 Variable Names

The column names are listed to identify and locate the variables available in the dataset.

In [5]:
df.columns.tolist()

['version',
 'doi',
 'A_YEAR',
 'B_COUNTRY',
 'B_COUNTRY_ALPHA',
 'C_COW_NUM',
 'C_COW_ALPHA',
 'D_INTERVIEW',
 'FW_START',
 'FW_END',
 'K_TIME_START',
 'K_TIME_END',
 'K_DURATION',
 'Q_MODE',
 'N_REGION_ISO',
 'N_REGION_WVS',
 'G_TOWNSIZE',
 'G_TOWNSIZE2',
 'H_SETTLEMENT',
 'H_URBRURAL',
 'O1_LONGITUDE',
 'O2_LATITUDE',
 'S_INTLANGUAGE',
 'LNGE_ISO',
 'E_RESPINT',
 'F_INTPRIVACY',
 'E1_LITERACY',
 'W_WEIGHT',
 'S018',
 'PWGHT',
 'Q1',
 'Q2',
 'Q3',
 'Q4',
 'Q5',
 'Q6',
 'Q7',
 'Q8',
 'Q9',
 'Q10',
 'Q11',
 'Q12',
 'Q13',
 'Q14',
 'Q15',
 'Q16',
 'Q17',
 'Q18',
 'Q19',
 'Q20',
 'Q21',
 'Q22',
 'Q23',
 'Q24',
 'Q25',
 'Q26',
 'Q27',
 'Q28',
 'Q29',
 'Q30',
 'Q31',
 'Q32',
 'Q33',
 'Q33_3',
 'Q34',
 'Q34_3',
 'Q35',
 'Q35_3',
 'Q36',
 'Q37',
 'Q38',
 'Q39',
 'Q40',
 'Q41',
 'Q42',
 'Q43',
 'Q44',
 'Q45',
 'Q46',
 'Q47',
 'Q48',
 'Q49',
 'Q50',
 'Q51',
 'Q52',
 'Q53',
 'Q54',
 'Q55',
 'Q56',
 'Q57',
 'Q58',
 'Q59',
 'Q60',
 'Q61',
 'Q62',
 'Q63',
 'Q64',
 'Q65',
 'Q66',
 'Q67',
 'Q68',
 'Q69',
 'Q70',
 'Q71',
 'Q72',
 'Q73',
 'Q74',
 'Q75',
 'Q76',
 'Q77',
 'Q78',
 'Q79',
 'Q80',
 'Q81',
 'Q82',
 'Q82_ASEAN',
 'Q83',
 'Q84',
 'Q85',
 'Q86',
 'Q87',
 'Q88',
 'Q89',
 'Q90',
 'Q91',
 'Q92',
 'Q93',
 'Q94',
 'Q95',
 'Q96',
 'Q97',
 'Q98',
 'Q99',
 'Q100',
 'Q101',
 'Q102',
 'Q103',
 'Q104',
 'Q105',
 'Q106',
 'Q107',
 'Q108',
 'Q109',
 'Q110',
 'Q111',
 'Q112',
 'Q113',
 'Q114',
 'Q116',
 'Q117',
 'Q118',
 'Q119',
 'Q120',
 'Q121',
 'Q122',
 'Q123',
 'Q124',
 'Q125',
 'Q126',
 'Q127',
 'Q128',
 'Q129',
 'Q130',
 'Q131',
 'Q132',
 'Q133',
 'Q134',
 'Q135',
 'Q136',
 'Q137',
 'Q138',
 'Q139',
 'Q140',
 'Q142',
 'Q143',
 'Q144',
 'Q145',
 'Q146',
 'Q147',
 'Q148',
 'Q149',
 'Q150',
 'Q151',
 'Q152',
 'Q153',
 'Q154',
 'Q155',
 'Q156',
 'Q157',
 'Q158',
 'Q159',
 'Q160',
 'Q161',
 'Q162',
 'Q163',
 'Q164',
 'Q165',
 'Q166',
 'Q167',
 'Q168',
 'Q169',
 'Q170',
 'Q171',
 'Q172',
 'Q173',
 'Q174',
 'Q175',
 'Q176',
 'Q177',
 'Q178',
 'Q179',
 'Q180',
 'Q181',
 'Q182',
 'Q183',
 'Q184',
 'Q185',
 'Q186',
 'Q187',
 'Q188',
 'Q189',
 'Q190',
 'Q191',
 'Q192',
 'Q193',
 'Q194',
 'Q195',
 'Q196',
 'Q197',
 'Q198',
 'Q199',
 'Q200',
 'Q201',
 'Q202',
 'Q203',
 'Q204',
 'Q205',
 'Q206',
 'Q207',
 'Q208',
 'Q209',
 'Q210',
 'Q211',
 'Q212',
 'Q213',
 'Q214',
 'Q215',
 'Q216',
 'Q217',
 'Q218',
 'Q219',
 'Q220',
 'Q222',
 'Q224',
 'Q225',
 'Q226',
 'Q227',
 'Q228',
 'Q229',
 'Q230',
 'Q231',
 'Q232',
 'Q233',
 'Q234',
 'Q234A',
 'Q235',
 'Q236',
 'Q237',
 'Q238',
 'Q239',
 'Q240',
 'Q241',
 'Q242',
 'Q243',
 'Q244',
 'Q245',
 'Q246',
 'Q247',
 'Q248',
 'Q249',
 'Q250',
 'Q251',
 'Q252',
 'Q253',
 'Q254',
 'Q257',
 'Q258',
 'Q259',
 'Q260',
 'Q261',
 'Q262',
 'X003R',
 'X003R2',
 'Q263',
 'Q264',
 'Q265',
 'Q266',
 'Q267',
 'Q268',
 'Q269',
 'Q270',
 'Q271',
 'Q272',
 'Q273',
 'Q274',
 'Q275',
 'Q275A',
 'Q275R',
 'Q276',
 'Q276A',
 'Q276R',
 'Q277',
 'Q277A',
 'Q277R',
 'Q278',
 'Q278A',
 'Q278R',
 'Q279',
 'Q280',
 'Q281',
 'Q282',
 'Q283',
 'Q284',
 'Q285',
 'Q286',
 'Q287',
 'Q288',
 'Q288R',
 'Q289',
 'Q289CS9',
 'Q290',
 'Y001',
 'Y002',
 'Y003',
 'SACSECVAL',
 'SACSECVALB',
 'RESEMAVAL',
 'RESEMAVALB',
 'I_AUTHORITY',
 'I_NATIONALISM',
 'I_DEVOUT',
 'DEFIANCE',
 'I_RELIGIMP',
 'I_RELIGBEL',
 'I_RELIGPRAC',
 'DISBELIEF',
 'I_NORM1',
 'I_NORM2',
 'I_NORM3',
 'RELATIVISM',
 'I_TRUSTARMY',
 'I_TRUSTPOLICE',
 'I_TRUSTCOURTS',
 'SCEPTICISM',
 'I_INDEP',
 'I_IMAGIN',
 'I_NONOBED',
 'AUTONOMY',
 'I_WOMJOB',
 'I_WOMPOL',
 'I_WOMEDU',
 'EQUALITY',
 'I_HOMOLIB',
 'I_ABORTLIB',
 'I_DIVORLIB',
 'CHOICE',
 'I_VOICE1',
 'I_VOICE2',
 'I_VOI2_00',
 'VOICE',
 'SECVALWGT',
 'WEIGHT1A',
 'WEIGHT1B',
 'WEIGHT2A',
 'WEIGHT2B',
 'WEIGHT3A',
 'WEIGHT3B',
 'WEIGHT4A',
 'WEIGHT4B',
 'RESEMAVALBWGT',
 'RESEMAVALWGT',
 'SECVALBWGT',
 'Y001_1',
 'Y001_2',
 'Y001_3',
 'Y001_4',
 'Y001_5']

### 2.4 Dataset Structure

The dataset structure is examined to review the number of observations, variables, data types, and non-null values.

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 2012 entries, 6-0-0 (2024-04-15) to 6-0-0 (2024-04-15)
Columns: 387 entries, version to Y001_5
dtypes: float64(383), str(4)
memory usage: 6.1 MB

## 3. Variable Selection

The variables relevant to the research question are selected from the full WVS dataset and copied into a separate DataFrame for further analysis.

In [7]:
variables = [
    "Q27", "Q28", "Q29", "Q30", "Q31", "Q32",
    "Q158", "Q159", "Q160", "Q161", "Q162", "Q163", "Q164",
    "Q275", "Q276", "Q277", "Q278",
]

df_selected = df[variables].copy()

### 3.1 Selected Variables

The structure of the selected variables is examined to confirm the number of observations, data types, and non-null values.

In [8]:
df_selected.info()

<class 'pandas.DataFrame'>
Index: 2012 entries, 6-0-0 (2024-04-15) to 6-0-0 (2024-04-15)
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q27     2012 non-null   float64
 1   Q28     2012 non-null   float64
 2   Q29     2012 non-null   float64
 3   Q30     2012 non-null   float64
 4   Q31     2012 non-null   float64
 5   Q32     2012 non-null   float64
 6   Q158    2012 non-null   float64
 7   Q159    2012 non-null   float64
 8   Q160    2012 non-null   float64
 9   Q161    2012 non-null   float64
 10  Q162    2012 non-null   float64
 11  Q163    2012 non-null   float64
 12  Q164    2012 non-null   float64
 13  Q275    2012 non-null   float64
 14  Q276    2012 non-null   float64
 15  Q277    2012 non-null   float64
 16  Q278    2012 non-null   float64
dtypes: float64(17)
memory usage: 318.3 KB

### 3.2 Inspect Selected Variables

The first five rows are displayed to verify that the selected variables have been correctly extracted from the dataset.

In [9]:
df_selected.head()

,Q27,Q28,Q29,Q30,Q31,Q32,Q158,Q159,Q160,Q161,Q162,Q163,Q164,Q275,Q276,Q277,Q278
6-0-0 (2024-04-15),4.0,1.0,4.0,2.0,3.0,2.0,9.0,7.0,3.0,10.0,9.0,9.0,1.0,702014.0,702013.0,702004.0,702004.0
6-0-0 (2024-04-15),2.0,1.0,1.0,1.0,2.0,4.0,3.0,8.0,6.0,3.0,2.0,7.0,1.0,702013.0,-3.0,-1.0,-1.0
6-0-0 (2024-04-15),3.0,4.0,4.0,3.0,1.0,4.0,8.0,4.0,4.0,9.0,6.0,3.0,2.0,702013.0,-3.0,702002.0,702004.0
6-0-0 (2024-04-15),3.0,4.0,4.0,4.0,4.0,5.0,7.0,6.0,6.0,2.0,6.0,1.0,2.0,702013.0,702013.0,702004.0,702004.0
6-0-0 (2024-04-15),1.0,4.0,4.0,4.0,4.0,5.0,3.0,9.0,9.0,10.0,10.0,10.0,1.0,702005.0,702009.0,702005.0,-1.0

### 3.3 Q27 to 32 Variables

The frequency distributions of Q27–Q32 are examined to identify response patterns, valid response categories, and missing-value codes.

In [10]:
for col in df_selected.columns:
    print("\n====================")
    print(col)
    print(df_selected[col].value_counts(dropna=False).sort_index())

====================
Q27
Q27
-2.0       8
 1.0     104
 2.0     603
 3.0    1079
 4.0     218
Name: count, dtype: int64

====================
Q28
Q28
-2.0      24
 1.0      98
 2.0     514
 3.0    1086
 4.0     290
Name: count, dtype: int64

====================
Q29
Q29
-2.0       7
 1.0      57
 2.0     293
 3.0    1070
 4.0     585
Name: count, dtype: int64

====================
Q30
Q30
-2.0      13
 1.0      45
 2.0     421
 3.0    1132
 4.0     401
Name: count, dtype: int64

====================
Q31
Q31
-2.0      16
 1.0     242
 2.0    1088
 3.0     555
 4.0     111
Name: count, dtype: int64

====================
Q32
Q32
-2.0      2
 1.0     94
 2.0    471
 3.0    393
 4.0    762
 5.0    290
Name: count, dtype: int64

====================
Q158
Q158
-2.0       5
 1.0      14
 2.0      25
 3.0      32
 4.0      62
 5.0     291
 6.0     198
 7.0     321
 8.0     515
 9.0     252
 10.0    297
Name: count, dtype: int64

====================
Q159
Q159
-2.0      19
 1.0     108
 2.0      98
 3.0     134
 4.0     117
 5.0     472
 6.0     221
 7.0     321
 8.0     304
 9.0     113
 10.0    105
Name: count, dtype: int64

====================
Q160
Q160
-2.0      23
 1.0     119
 2.0     108
 3.0     163
 4.0     109
 5.0     542
 6.0     260
 7.0     272
 8.0     248
 9.0      85
 10.0     83
Name: count, dtype: int64

====================
Q161
Q161
-2.0       4
 1.0     398
 2.0     282
 3.0     357
 4.0     228
 5.0     348
 6.0     110
 7.0     113
 8.0      88
 9.0      21
 10.0     63
Name: count, dtype: int64

====================
Q162
Q162
-2.0       9
 1.0      37
 2.0      44
 3.0      91
 4.0     104
 5.0     343
 6.0     250
 7.0     367
 8.0     418
 9.0     178
 10.0    171
Name: count, dtype: int64

====================
Q163
Q163
-2.0      11
 1.0     173
 2.0      74
 3.0     108
 4.0      64
 5.0     308
 6.0     141
 7.0     176
 8.0     258
 9.0     116
 10.0    583
Name: count, dtype: int64

====================
Q164
Q164
-2.0      50
 1.0    1582
 2.0     380
Name: count, dtype: int64

====================
Q275
Q275
-2.0           4
 702001.0     37
 702002.0     80
 702003.0    126
 702004.0    130
 702005.0    341
 702006.0     39
 702007.0     71
 702008.0    114
 702009.0    345
 702010.0     48
 702012.0      9
 702013.0    496
 702014.0    155
 702015.0     17
Name: count, dtype: int64

====================
Q276
Q276
-3.0         803
-2.0           5
-1.0           5
 702001.0     26
 702002.0     50
 702003.0     84
 702004.0     75
 702005.0    253
 702006.0     24
 702007.0     35
 702008.0     62
 702009.0    158
 702010.0     19
 702012.0      6
 702013.0    282
 702014.0    106
 702015.0     19
Name: count, dtype: int64

====================
Q277
Q277
-5.0           1
-2.0           9
-1.0         116
 702001.0    693
 702002.0    256
 702003.0    186
 702004.0    167
 702005.0    299
 702006.0      8
 702007.0      9
 702008.0     66
 702009.0     76
 702010.0     25
 702012.0      4
 702013.0     77
 702014.0     18
 702015.0      2
Name: count, dtype: int64

====================
Q278
Q278
-3.0           1
-2.0          10
-1.0         174
 702001.0    461
 702002.0    283
 702003.0    181
 702004.0    181
 702005.0    305
 702006.0     36
 702007.0     22
 702008.0     80
 702009.0     86
 702010.0     20
 702012.0      5
 702013.0    129
 702014.0     31
 702015.0      7
Name: count, dtype: int64

### 3.4 Checking Q164 Coding

The unique values of Q164 are examined to verify its response categories and identify any special or missing-value codes.

In [11]:
print(df["Q164"].unique())

[ 1.  2. -2.]

### 3.5 Identifying Q164-Related Variables

The dataset is searched for all column names containing "164" to identify related variables and verify the correct variable coding.

In [12]:
[col for col in df.columns if "164" in col]

['Q164']

### 3.6 Verifying Q158–Q165 Variable Alignment

The frequency distributions of Q158–Q165 are compared to verify the correct alignment of the dataset variables with the WVS codebook.

In [13]:
for q in ["Q158", "Q159", "Q160", "Q161", "Q162", "Q163", "Q164", "Q165"]:
    print(q, df[q].value_counts(dropna=False).sort_index().to_dict())

Q158 {-2.0: 5, 1.0: 14, 2.0: 25, 3.0: 32, 4.0: 62, 5.0: 291, 6.0: 198, 7.0: 321, 8.0: 515, 9.0: 252, 10.0: 297}
Q159 {-2.0: 19, 1.0: 108, 2.0: 98, 3.0: 134, 4.0: 117, 5.0: 472, 6.0: 221, 7.0: 321, 8.0: 304, 9.0: 113, 10.0: 105}
Q160 {-2.0: 23, 1.0: 119, 2.0: 108, 3.0: 163, 4.0: 109, 5.0: 542, 6.0: 260, 7.0: 272, 8.0: 248, 9.0: 85, 10.0: 83}
Q161 {-2.0: 4, 1.0: 398, 2.0: 282, 3.0: 357, 4.0: 228, 5.0: 348, 6.0: 110, 7.0: 113, 8.0: 88, 9.0: 21, 10.0: 63}
Q162 {-2.0: 9, 1.0: 37, 2.0: 44, 3.0: 91, 4.0: 104, 5.0: 343, 6.0: 250, 7.0: 367, 8.0: 418, 9.0: 178, 10.0: 171}
Q163 {-2.0: 11, 1.0: 173, 2.0: 74, 3.0: 108, 4.0: 64, 5.0: 308, 6.0: 141, 7.0: 176, 8.0: 258, 9.0: 116, 10.0: 583}
Q164 {-2.0: 50, 1.0: 1582, 2.0: 380}
Q165 {-2.0: 88, 1.0: 1343, 2.0: 581}

### 3.7 Verifying Q27–Q32 Variable Alignment

The frequency distributions of Q26–Q33 are examined to verify the alignment of the dataset variables with the corresponding WVS codebook questions.

In [14]:
for q in [f"Q{i}" for i in range(26, 34)]:
    print("\n", q)
    print(df[q].value_counts(dropna=False).sort_index())

 Q26
Q26
-2.0      11
 1.0     576
 2.0    1148
 3.0     254
 4.0      23
Name: count, dtype: int64

 Q27
Q27
-2.0       8
 1.0     104
 2.0     603
 3.0    1079
 4.0     218
Name: count, dtype: int64

 Q28
Q28
-2.0      24
 1.0      98
 2.0     514
 3.0    1086
 4.0     290
Name: count, dtype: int64

 Q29
Q29
-2.0       7
 1.0      57
 2.0     293
 3.0    1070
 4.0     585
Name: count, dtype: int64

 Q30
Q30
-2.0      13
 1.0      45
 2.0     421
 3.0    1132
 4.0     401
Name: count, dtype: int64

 Q31
Q31
-2.0      16
 1.0     242
 2.0    1088
 3.0     555
 4.0     111
Name: count, dtype: int64

 Q32
Q32
-2.0      2
 1.0     94
 2.0    471
 3.0    393
 4.0    762
 5.0    290
Name: count, dtype: int64

 Q33
Q33
-2.0       2
 1.0     565
 2.0    1052
 3.0     393
Name: count, dtype: int64

### 3.8 Mapping Q27–Q32 to the WVS Codebook

The dataset columns are mapped to their corresponding WVS codebook questions to account for the identified one-column offset. A new DataFrame is created using the correct codebook question labels.

In [15]:
q27_q32_mapping = {
    "Q27": "Q26",
    "Q28": "Q27",
    "Q29": "Q28",
    "Q30": "Q29",
    "Q31": "Q30",
    "Q32": "Q31"
}

df_q27_q32 = pd.DataFrame({
    codebook_q: df[dataset_q]
    for codebook_q, dataset_q in q27_q32_mapping.items()
})

### 3.9 Inspect Corrected Q27

The corrected Q27 variable is displayed to verify that the dataset column has been correctly mapped to the WVS codebook question.

In [16]:
df_q27_q32["Q27"]

6-0-0 (2024-04-15)    3.0
6-0-0 (2024-04-15)    2.0
6-0-0 (2024-04-15)    2.0
6-0-0 (2024-04-15)    2.0
6-0-0 (2024-04-15)    2.0
                     ...
6-0-0 (2024-04-15)    2.0
6-0-0 (2024-04-15)    2.0
6-0-0 (2024-04-15)    2.0
6-0-0 (2024-04-15)    2.0
6-0-0 (2024-04-15)    2.0
Name: Q27, Length: 2012, dtype: float64

### 3.10 Verify Corrected Q27–Q32 Variables

The first five observations and frequency distribution of Q27 are examined to confirm that the codebook-to-dataset mapping has been applied correctly.

In [17]:
print(df_q27_q32.head())
print(df_q27_q32["Q27"].value_counts(dropna=False).sort_index())

                    Q27  Q28  Q29  Q30  Q31  Q32
6-0-0 (2024-04-15)  3.0  4.0  1.0  4.0  2.0  3.0
6-0-0 (2024-04-15)  2.0  2.0  1.0  1.0  1.0  2.0
6-0-0 (2024-04-15)  2.0  3.0  4.0  4.0  3.0  1.0
6-0-0 (2024-04-15)  2.0  3.0  4.0  4.0  4.0  4.0
6-0-0 (2024-04-15)  2.0  1.0  4.0  4.0  4.0  4.0
Q27
-2.0      11
 1.0     576
 2.0    1148
 3.0     254
 4.0      23
Name: count, dtype: int64

### 3.11 Check Q27–Q32 Distributions

The frequency distributions of all corrected Q27–Q32 variables are examined to verify their response categories and identify any missing-value codes.

In [18]:
for q in df_q27_q32.columns:
    print("\n", q)
    print(df_q27_q32[q].value_counts(dropna=False).sort_index())

 Q27
Q27
-2.0      11
 1.0     576
 2.0    1148
 3.0     254
 4.0      23
Name: count, dtype: int64

 Q28
Q28
-2.0       8
 1.0     104
 2.0     603
 3.0    1079
 4.0     218
Name: count, dtype: int64

 Q29
Q29
-2.0      24
 1.0      98
 2.0     514
 3.0    1086
 4.0     290
Name: count, dtype: int64

 Q30
Q30
-2.0       7
 1.0      57
 2.0     293
 3.0    1070
 4.0     585
Name: count, dtype: int64

 Q31
Q31
-2.0      13
 1.0      45
 2.0     421
 3.0    1132
 4.0     401
Name: count, dtype: int64

 Q32
Q32
-2.0      16
 1.0     242
 2.0    1088
 3.0     555
 4.0     111
Name: count, dtype: int64

### 3.12 Verifying Q158–Q164 Variable Alignment

The frequency distributions of Q157–Q165 are examined to verify the alignment of the dataset variables with the corresponding WVS codebook questions.

In [19]:
for q in [f"Q{i}" for i in range(157, 166)]:
    print("\n", q)
    print(df[q].value_counts(dropna=False).sort_index())

 Q157
Q157
-2.0       5
 1.0      12
 2.0      18
 3.0      27
 4.0      35
 5.0     314
 6.0     197
 7.0     302
 8.0     569
 9.0     240
 10.0    293
Name: count, dtype: int64

 Q158
Q158
-2.0       5
 1.0      14
 2.0      25
 3.0      32
 4.0      62
 5.0     291
 6.0     198
 7.0     321
 8.0     515
 9.0     252
 10.0    297
Name: count, dtype: int64

 Q159
Q159
-2.0      19
 1.0     108
 2.0      98
 3.0     134
 4.0     117
 5.0     472
 6.0     221
 7.0     321
 8.0     304
 9.0     113
 10.0    105
Name: count, dtype: int64

 Q160
Q160
-2.0      23
 1.0     119
 2.0     108
 3.0     163
 4.0     109
 5.0     542
 6.0     260
 7.0     272
 8.0     248
 9.0      85
 10.0     83
Name: count, dtype: int64

 Q161
Q161
-2.0       4
 1.0     398
 2.0     282
 3.0     357
 4.0     228
 5.0     348
 6.0     110
 7.0     113
 8.0      88
 9.0      21
 10.0     63
Name: count, dtype: int64

 Q162
Q162
-2.0       9
 1.0      37
 2.0      44
 3.0      91
 4.0     104
 5.0     343
 6.0     250
 7.0     367
 8.0     418
 9.0     178
 10.0    171
Name: count, dtype: int64

 Q163
Q163
-2.0      11
 1.0     173
 2.0      74
 3.0     108
 4.0      64
 5.0     308
 6.0     141
 7.0     176
 8.0     258
 9.0     116
 10.0    583
Name: count, dtype: int64

 Q164
Q164
-2.0      50
 1.0    1582
 2.0     380
Name: count, dtype: int64

 Q165
Q165
-2.0      88
 1.0    1343
 2.0     581
Name: count, dtype: int64

### 3.13 Mapping Q158–Q164 to the WVS Codebook

The dataset columns are mapped to their corresponding WVS codebook questions to account for the identified one-column offset. A new DataFrame is created using the correct codebook question labels.

In [20]:
q158_q164_mapping = {
    "Q158": "Q157",
    "Q159": "Q158",
    "Q160": "Q159",
    "Q161": "Q160",
    "Q162": "Q161",
    "Q163": "Q162",
    "Q164": "Q163"
}

df_q158_q164 = pd.DataFrame({
    codebook_q: df[dataset_q]
    for codebook_q, dataset_q in q158_q164_mapping.items()
})

### 3.14 Check Q158–Q164 Distributions

The frequency distributions of all corrected Q158–Q164 variables are examined to verify their response categories and identify any missing-value codes.

In [21]:
for q in df_q158_q164.columns:
    print("\n", q)
    print(df_q158_q164[q].value_counts(dropna=False).sort_index())

 Q158
Q158
-2.0       5
 1.0      12
 2.0      18
 3.0      27
 4.0      35
 5.0     314
 6.0     197
 7.0     302
 8.0     569
 9.0     240
 10.0    293
Name: count, dtype: int64

 Q159
Q159
-2.0       5
 1.0      14
 2.0      25
 3.0      32
 4.0      62
 5.0     291
 6.0     198
 7.0     321
 8.0     515
 9.0     252
 10.0    297
Name: count, dtype: int64

 Q160
Q160
-2.0      19
 1.0     108
 2.0      98
 3.0     134
 4.0     117
 5.0     472
 6.0     221
 7.0     321
 8.0     304
 9.0     113
 10.0    105
Name: count, dtype: int64

 Q161
Q161
-2.0      23
 1.0     119
 2.0     108
 3.0     163
 4.0     109
 5.0     542
 6.0     260
 7.0     272
 8.0     248
 9.0      85
 10.0     83
Name: count, dtype: int64

 Q162
Q162
-2.0       4
 1.0     398
 2.0     282
 3.0     357
 4.0     228
 5.0     348
 6.0     110
 7.0     113
 8.0      88
 9.0      21
 10.0     63
Name: count, dtype: int64

 Q163
Q163
-2.0       9
 1.0      37
 2.0      44
 3.0      91
 4.0     104
 5.0     343
 6.0     250
 7.0     367
 8.0     418
 9.0     178
 10.0    171
Name: count, dtype: int64

 Q164
Q164
-2.0      11
 1.0     173
 2.0      74
 3.0     108
 4.0      64
 5.0     308
 6.0     141
 7.0     176
 8.0     258
 9.0     116
 10.0    583
Name: count, dtype: int64

### 3.15 Verifying Q275 to 278 Variables Alignment

The frequency distributions of the education-related variables and surrounding questions are examined to identify the one-column offset and verify the correspondence between dataset columns and WVS codebook questions.

In [22]:
for q in ["Q272", "Q273", "Q274", "Q275", "Q275A", "Q275R", "Q276", "Q276A", "Q276R",
          "Q277", "Q277A", "Q277R"]:
    print("\n", q)
    print(df[q].value_counts(dropna=False).sort_index())

 Q272
Q272
1.0    1188
2.0      21
3.0      88
4.0      18
5.0      96
6.0     601
Name: count, dtype: int64

 Q273
Q273
-2.0      28
 0.0     757
 1.0     294
 2.0     545
 3.0     278
 4.0      84
 5.0      13
 6.0       8
 7.0       2
 8.0       1
 10.0      2
Name: count, dtype: int64

 Q274
Q274
-2.0      4
 0.0    117
 1.0    126
 2.0    130
 3.0    341
 4.0    272
 5.0    348
 6.0    502
 7.0    155
 8.0     17
Name: count, dtype: int64

 Q275
Q275
-2.0           4
 702001.0     37
 702002.0     80
 702003.0    126
 702004.0    130
 702005.0    341
 702006.0     39
 702007.0     71
 702008.0    114
 702009.0    345
 702010.0     48
 702012.0      9
 702013.0    496
 702014.0    155
 702015.0     17
Name: count, dtype: int64

 Q275A
Q275A
-2.0       4
 1.0     373
 2.0     613
 3.0    1022
Name: count, dtype: int64

 Q275R
Q275R
-3.0    803
-2.0      5
-1.0      5
 0.0     76
 1.0     84
 2.0     75
 3.0    253
 4.0    140
 5.0    158
 6.0    288
 7.0    106
 8.0     19
Name: count, dtype: int64

 Q276
Q276
-3.0         803
-2.0           5
-1.0           5
 702001.0     26
 702002.0     50
 702003.0     84
 702004.0     75
 702005.0    253
 702006.0     24
 702007.0     35
 702008.0     62
 702009.0    158
 702010.0     19
 702012.0      6
 702013.0    282
 702014.0    106
 702015.0     19
Name: count, dtype: int64

 Q276A
Q276A
-3.0    803
-2.0      5
-1.0      5
 1.0    235
 2.0    393
 3.0    571
Name: count, dtype: int64

 Q276R
Q276R
-5.0      1
-2.0      9
-1.0    116
 0.0    949
 1.0    186
 2.0    167
 3.0    299
 4.0    108
 5.0     79
 6.0     78
 7.0     18
 8.0      2
Name: count, dtype: int64

 Q277
Q277
-5.0           1
-2.0           9
-1.0         116
 702001.0    693
 702002.0    256
 702003.0    186
 702004.0    167
 702005.0    299
 702006.0      8
 702007.0      9
 702008.0     66
 702009.0     76
 702010.0     25
 702012.0      4
 702013.0     77
 702014.0     18
 702015.0      2
Name: count, dtype: int64

 Q277A
Q277A
-5.0       1
-2.0       9
-1.0     116
 1.0    1302
 2.0     407
 3.0     177
Name: count, dtype: int64

 Q277R
Q277R
-3.0      1
-2.0     10
-1.0    174
 0.0    744
 1.0    181
 2.0    181
 3.0    305
 4.0    158
 5.0     88
 6.0    132
 7.0     31
 8.0      7
Name: count, dtype: int64

### 3.16 Mapping Q277 and 278 Variables

The dataset columns are mapped to the corresponding WVS codebook questions for mother's and father's educational attainment. The original, country-specific, and recoded versions are retained for comparison and variable selection.

In [23]:
q277_q278_mapping = {
    "Q277": "Q276",      # Mother's education
    "Q277A": "Q277",     # Mother's country-specific education
    "Q277R": "Q277A",   # Mother's recoded education
    
    "Q278": "Q277",      # Father's education
    "Q278A": "Q278",     # Father's country-specific education
    "Q278R": "Q278A"     # Father's recoded education
}

# Create a new dataframe using the correct codebook labels
df_q277_q278 = pd.DataFrame({
    codebook_q: df[dataset_q]
    for codebook_q, dataset_q in q277_q278_mapping.items()
})

# Check the result
df_q277_q278.head()

                        Q277     Q277A  Q277R      Q278     Q278A  Q278R
6-0-0 (2024-04-15)  702013.0  702004.0    1.0  702004.0  702004.0    1.0
6-0-0 (2024-04-15)      -3.0      -1.0   -1.0      -1.0      -1.0   -1.0
6-0-0 (2024-04-15)      -3.0  702002.0    1.0  702002.0  702004.0    1.0
6-0-0 (2024-04-15)  702013.0  702004.0    1.0  702004.0  702004.0    1.0
6-0-0 (2024-04-15)  702009.0  702005.0    2.0  702005.0      -1.0   -1.0

### 3.17 Check Q277 and 278 Distributions

The frequency distributions of the corrected parental education variables are examined to compare the original, country-specific, and recoded measures and identify missing-value codes.

In [24]:
for col in df_q277_q278.columns:
    print("\n====================")
    print(col)
    print(df_q277_q278[col].value_counts(dropna=False).sort_index())

====================
Q277
Q277
-3.0         803
-2.0           5
-1.0           5
 702001.0     26
 702002.0     50
 702003.0     84
 702004.0     75
 702005.0    253
 702006.0     24
 702007.0     35
 702008.0     62
 702009.0    158
 702010.0     19
 702012.0      6
 702013.0    282
 702014.0    106
 702015.0     19
Name: count, dtype: int64

====================
Q277A
Q277A
-5.0           1
-2.0           9
-1.0         116
 702001.0    693
 702002.0    256
 702003.0    186
 702004.0    167
 702005.0    299
 702006.0      8
 702007.0      9
 702008.0     66
 702009.0     76
 702010.0     25
 702012.0      4
 702013.0     77
 702014.0     18
 702015.0      2
Name: count, dtype: int64

====================
Q277R
Q277R
-5.0       1
-2.0       9
-1.0     116
 1.0    1302
 2.0     407
 3.0     177
Name: count, dtype: int64

====================
Q278
Q278
-5.0           1
-2.0           9
-1.0         116
 702001.0    693
 702002.0    256
 702003.0    186
 702004.0    167
 702005.0    299
 702006.0      8
 702007.0      9
 702008.0     66
 702009.0     76
 702010.0     25
 702012.0      4
 702013.0     77
 702014.0     18
 702015.0      2
Name: count, dtype: int64

====================
Q278A
Q278A
-3.0           1
-2.0          10
-1.0         174
 702001.0    461
 702002.0    283
 702003.0    181
 702004.0    181
 702005.0    305
 702006.0     36
 702007.0     22
 702008.0     80
 702009.0     86
 702010.0     20
 702012.0      5
 702013.0    129
 702014.0     31
 702015.0      7
Name: count, dtype: int64

====================
Q278R
Q278R
-3.0       1
-2.0      10
-1.0     174
 1.0    1106
 2.0     463
 3.0     258
Name: count, dtype: int64

### 3.18 Creating the Mapped Dataset

The verified codebook-to-dataset mappings are combined into a single DataFrame. This creates a working dataset containing Q27-Q32, Q158–Q164, and Q277-278 variables under their correct WVS codebook labels.

In [25]:
# Map codebook question numbers to actual dataset columns
all_mapping = {
    # Gender-role attitudes
    "Q27": "Q26",
    "Q28": "Q27",
    "Q29": "Q28",
    "Q30": "Q29",
    "Q31": "Q30",
    "Q32": "Q31",

    # Q158–Q164
    "Q158": "Q157",
    "Q159": "Q158",
    "Q160": "Q159",
    "Q161": "Q160",
    "Q162": "Q161",
    "Q163": "Q162",
    "Q164": "Q163",

    # Mother's education
    "Q277": "Q276",
    "Q277A": "Q277",
    "Q277R": "Q277A",

    # Father's education
    "Q278": "Q277",
    "Q278A": "Q278",
    "Q278R": "Q278A"
}

df_selected = pd.DataFrame({
    codebook_q: df[dataset_q]
    for codebook_q, dataset_q in all_mapping.items()
})

df_selected.head()

,Q27,Q28,Q29,Q30,Q31,Q32,Q158,Q159,Q160,Q161,Q162,Q163,Q164,Q277,Q277A,Q277R,Q278,Q278A,Q278R
6-0-0 (2024-04-15),3.0,4.0,1.0,4.0,2.0,3.0,10.0,9.0,7.0,3.0,10.0,9.0,9.0,702013.0,702004.0,1.0,702004.0,702004.0,1.0
6-0-0 (2024-04-15),2.0,2.0,1.0,1.0,1.0,2.0,7.0,3.0,8.0,6.0,3.0,2.0,7.0,-3.0,-1.0,-1.0,-1.0,-1.0,-1.0
6-0-0 (2024-04-15),2.0,3.0,4.0,4.0,3.0,1.0,7.0,8.0,4.0,4.0,9.0,6.0,3.0,-3.0,702002.0,1.0,702002.0,702004.0,1.0
6-0-0 (2024-04-15),2.0,3.0,4.0,4.0,4.0,4.0,7.0,7.0,6.0,6.0,2.0,6.0,1.0,702013.0,702004.0,1.0,702004.0,702004.0,1.0
6-0-0 (2024-04-15),2.0,1.0,4.0,4.0,4.0,4.0,5.0,3.0,9.0,9.0,10.0,10.0,10.0,702009.0,702005.0,2.0,702005.0,-1.0,-1.0

### 3.19 Verify Mapped Dataset Structure

The structure of the combined dataset is examined to confirm the number of observations, variables, and data types after applying the codebook-to-dataset mappings.

In [26]:
df_selected.info()

<class 'pandas.DataFrame'>
Index: 2012 entries, 6-0-0 (2024-04-15) to 6-0-0 (2024-04-15)
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q27     2012 non-null   float64
 1   Q28     2012 non-null   float64
 2   Q29     2012 non-null   float64
 3   Q30     2012 non-null   float64
 4   Q31     2012 non-null   float64
 5   Q32     2012 non-null   float64
 6   Q158    2012 non-null   float64
 7   Q159    2012 non-null   float64
 8   Q160    2012 non-null   float64
 9   Q161    2012 non-null   float64
 10  Q162    2012 non-null   float64
 11  Q163    2012 non-null   float64
 12  Q164    2012 non-null   float64
 13  Q277    2012 non-null   float64
 14  Q277A   2012 non-null   float64
 15  Q277R   2012 non-null   float64
 16  Q278    2012 non-null   float64
 17  Q278A   2012 non-null   float64
 18  Q278R   2012 non-null   float64
dtypes: float64(19)
memory usage: 414.3 KB

### 3.20 Check Mapped Variable Distributions

The frequency distributions of all mapped variables are examined to verify their response categories, coding schemes, and missing-value codes before data cleaning and transformation.

In [27]:
for col in df_selected.columns:
    print("\n====================")
    print(col)
    print(df_selected[col].value_counts(dropna=False).sort_index())

====================
Q27
Q27
-2.0      11
 1.0     576
 2.0    1148
 3.0     254
 4.0      23
Name: count, dtype: int64

====================
Q28
Q28
-2.0       8
 1.0     104
 2.0     603
 3.0    1079
 4.0     218
Name: count, dtype: int64

====================
Q29
Q29
-2.0      24
 1.0      98
 2.0     514
 3.0    1086
 4.0     290
Name: count, dtype: int64

====================
Q30
Q30
-2.0       7
 1.0      57
 2.0     293
 3.0    1070
 4.0     585
Name: count, dtype: int64

====================
Q31
Q31
-2.0      13
 1.0      45
 2.0     421
 3.0    1132
 4.0     401
Name: count, dtype: int64

====================
Q32
Q32
-2.0      16
 1.0     242
 2.0    1088
 3.0     555
 4.0     111
Name: count, dtype: int64

====================
Q158
Q158
-2.0       5
 1.0      12
 2.0      18
 3.0      27
 4.0      35
 5.0     314
 6.0     197
 7.0     302
 8.0     569
 9.0     240
 10.0    293
Name: count, dtype: int64

====================
Q159
Q159
-2.0       5
 1.0      14
 2.0      25
 3.0      32
 4.0      62
 5.0     291
 6.0     198
 7.0     321
 8.0     515
 9.0     252
 10.0    297
Name: count, dtype: int64

====================
Q160
Q160
-2.0      19
 1.0     108
 2.0      98
 3.0     134
 4.0     117
 5.0     472
 6.0     221
 7.0     321
 8.0     304
 9.0     113
 10.0    105
Name: count, dtype: int64

====================
Q161
Q161
-2.0      23
 1.0     119
 2.0     108
 3.0     163
 4.0     109
 5.0     542
 6.0     260
 7.0     272
 8.0     248
 9.0      85
 10.0     83
Name: count, dtype: int64

====================
Q162
Q162
-2.0       4
 1.0     398
 2.0     282
 3.0     357
 4.0     228
 5.0     348
 6.0     110
 7.0     113
 8.0      88
 9.0      21
 10.0     63
Name: count, dtype: int64

====================
Q163
Q163
-2.0       9
 1.0      37
 2.0      44
 3.0      91
 4.0     104
 5.0     343
 6.0     250
 7.0     367
 8.0     418
 9.0     178
 10.0    171
Name: count, dtype: int64

====================
Q164
Q164
-2.0      11
 1.0     173
 2.0      74
 3.0     108
 4.0      64
 5.0     308
 6.0     141
 7.0     176
 8.0     258
 9.0     116
 10.0    583
Name: count, dtype: int64

====================
Q277
Q277
-3.0         803
-2.0           5
-1.0           5
 702001.0     26
 702002.0     50
 702003.0     84
 702004.0     75
 702005.0    253
 702006.0     24
 702007.0     35
 702008.0     62
 702009.0    158
 702010.0     19
 702012.0      6
 702013.0    282
 702014.0    106
 702015.0     19
Name: count, dtype: int64

====================
Q277A
Q277A
-5.0           1
-2.0           9
-1.0         116
 702001.0    693
 702002.0    256
 702003.0    186
 702004.0    167
 702005.0    299
 702006.0      8
 702007.0      9
 702008.0     66
 702009.0     76
 702010.0     25
 702012.0      4
 702013.0     77
 702014.0     18
 702015.0      2
Name: count, dtype: int64

====================
Q277R
Q277R
-5.0       1
-2.0       9
-1.0     116
 1.0    1302
 2.0     407
 3.0     177
Name: count, dtype: int64

====================
Q278
Q278
-5.0           1
-2.0           9
-1.0         116
 702001.0    693
 702002.0    256
 702003.0    186
 702004.0    167
 702005.0    299
 702006.0      8
 702007.0      9
 702008.0     66
 702009.0     76
 702010.0     25
 702012.0      4
 702013.0     77
 702014.0     18
 702015.0      2
Name: count, dtype: int64

====================
Q278A
Q278A
-3.0           1
-2.0          10
-1.0         174
 702001.0    461
 702002.0    283
 702003.0    181
 702004.0    181
 702005.0    305
 702006.0     36
 702007.0     22
 702008.0     80
 702009.0     86
 702010.0     20
 702012.0      5
 702013.0    129
 702014.0     31
 702015.0      7
Name: count, dtype: int64

====================
Q278R
Q278R
-3.0       1
-2.0      10
-1.0     174
 1.0    1106
 2.0     463
 3.0     258
Name: count, dtype: int64

### 3.21 Creating the Final Mapped Dataset

The verified codebook-to-dataset mappings are combined into a single DataFrame, retaining only the selected variables, including the recoded parental education measures Q277R and Q278R.

In [28]:
# Map selected variables to their corresponding WVS codebook questions
all_mapping = {
    # Gender-role attitudes
    "Q27": "Q26",
    "Q28": "Q27",
    "Q29": "Q28",
    "Q30": "Q29",
    "Q31": "Q30",
    "Q32": "Q31",

    # Q158–Q164
    "Q158": "Q157",
    "Q159": "Q158",
    "Q160": "Q159",
    "Q161": "Q160",
    "Q162": "Q161",
    "Q163": "Q162",
    "Q164": "Q163",

    # Mother's recoded education
    "Q277R": "Q277A",

    # Father's recoded education
    "Q278R": "Q278A"
}

df_selected = pd.DataFrame({
    codebook_q: df[dataset_q]
    for codebook_q, dataset_q in all_mapping.items()
})

df_selected.head()

,Q27,Q28,Q29,Q30,Q31,Q32,Q158,Q159,Q160,Q161,Q162,Q163,Q164,Q277R,Q278R
6-0-0 (2024-04-15),3.0,4.0,1.0,4.0,2.0,3.0,10.0,9.0,7.0,3.0,10.0,9.0,9.0,1.0,1.0
6-0-0 (2024-04-15),2.0,2.0,1.0,1.0,1.0,2.0,7.0,3.0,8.0,6.0,3.0,2.0,7.0,-1.0,-1.0
6-0-0 (2024-04-15),2.0,3.0,4.0,4.0,3.0,1.0,7.0,8.0,4.0,4.0,9.0,6.0,3.0,1.0,1.0
6-0-0 (2024-04-15),2.0,3.0,4.0,4.0,4.0,4.0,7.0,7.0,6.0,6.0,2.0,6.0,1.0,1.0,1.0
6-0-0 (2024-04-15),2.0,1.0,4.0,4.0,4.0,4.0,5.0,3.0,9.0,9.0,10.0,10.0,10.0,2.0,-1.0

### 3.21 Check Final Variable Distributions

The frequency distributions of all selected variables are examined to verify their response categories, coding schemes, and missing-value codes before data cleaning and transformation.

In [29]:
for col in df_selected.columns:
    print("\n====================")
    print(col)
    print(df_selected[col].value_counts(dropna=False).sort_index())

====================
Q27
Q27
-2.0      11
 1.0     576
 2.0    1148
 3.0     254
 4.0      23
Name: count, dtype: int64

====================
Q28
Q28
-2.0       8
 1.0     104
 2.0     603
 3.0    1079
 4.0     218
Name: count, dtype: int64

====================
Q29
Q29
-2.0      24
 1.0      98
 2.0     514
 3.0    1086
 4.0     290
Name: count, dtype: int64

====================
Q30
Q30
-2.0       7
 1.0      57
 2.0     293
 3.0    1070
 4.0     585
Name: count, dtype: int64

====================
Q31
Q31
-2.0      13
 1.0      45
 2.0     421
 3.0    1132
 4.0     401
Name: count, dtype: int64

====================
Q32
Q32
-2.0      16
 1.0     242
 2.0    1088
 3.0     555
 4.0     111
Name: count, dtype: int64

====================
Q158
Q158
-2.0       5
 1.0      12
 2.0      18
 3.0      27
 4.0      35
 5.0     314
 6.0     197
 7.0     302
 8.0     569
 9.0     240
 10.0    293
Name: count, dtype: int64

====================
Q159
Q159
-2.0       5
 1.0      14
 2.0      25
 3.0      32
 4.0      62
 5.0     291
 6.0     198
 7.0     321
 8.0     515
 9.0     252
 10.0    297
Name: count, dtype: int64

====================
Q160
Q160
-2.0      19
 1.0     108
 2.0      98
 3.0     134
 4.0     117
 5.0     472
 6.0     221
 7.0     321
 8.0     304
 9.0     113
 10.0    105
Name: count, dtype: int64

====================
Q161
Q161
-2.0      23
 1.0     119
 2.0     108
 3.0     163
 4.0     109
 5.0     542
 6.0     260
 7.0     272
 8.0     248
 9.0      85
 10.0     83
Name: count, dtype: int64

====================
Q162
Q162
-2.0       4
 1.0     398
 2.0     282
 3.0     357
 4.0     228
 5.0     348
 6.0     110
 7.0     113
 8.0      88
 9.0      21
 10.0     63
Name: count, dtype: int64

====================
Q163
Q163
-2.0       9
 1.0      37
 2.0      44
 3.0      91
 4.0     104
 5.0     343
 6.0     250
 7.0     367
 8.0     418
 9.0     178
 10.0    171
Name: count, dtype: int64

====================
Q164
Q164
-2.0      11
 1.0     173
 2.0      74
 3.0     108
 4.0      64
 5.0     308
 6.0     141
 7.0     176
 8.0     258
 9.0     116
 10.0    583
Name: count, dtype: int64

====================
Q277R
Q277R
-5.0       1
-2.0       9
-1.0     116
 1.0    1302
 2.0     407
 3.0     177
Name: count, dtype: int64

====================
Q278R
Q278R
-3.0       1
-2.0      10
-1.0     174
 1.0    1106
 2.0     463
 3.0     258
Name: count, dtype: int64

## 4. Data Recoding and Transformation

This section recodes missing-value codes and transforms selected variables to prepare them for statistical analysis.

### 4.1 Recode WVS Missing-Value Codes

The WVS missing-value codes are recoded as `NaN` across all selected variables to distinguish missing responses from valid response categories.

In [41]:
# Recode WVS missing-value codes as NaN across all selected variables
df_clean = df_selected.replace([-1, -2, -3, -4, -5], np.nan)

### 4.2 Check Variables After Missing-Value Recoding

The frequency distributions of all selected variables are examined to confirm that the WVS missing-value codes have been successfully recoded as `NaN`.

In [31]:
for col in df_clean.columns:
    print("\n====================")
    print(col)
    print(df_clean[col].value_counts(dropna=False).sort_index())

====================
Q27
Q27
1.0     576
2.0    1148
3.0     254
4.0      23
NaN      11
Name: count, dtype: int64

====================
Q28
Q28
1.0     104
2.0     603
3.0    1079
4.0     218
NaN       8
Name: count, dtype: int64

====================
Q29
Q29
1.0      98
2.0     514
3.0    1086
4.0     290
NaN      24
Name: count, dtype: int64

====================
Q30
Q30
1.0      57
2.0     293
3.0    1070
4.0     585
NaN       7
Name: count, dtype: int64

====================
Q31
Q31
1.0      45
2.0     421
3.0    1132
4.0     401
NaN      13
Name: count, dtype: int64

====================
Q32
Q32
1.0     242
2.0    1088
3.0     555
4.0     111
NaN      16
Name: count, dtype: int64

====================
Q158
Q158
1.0      12
2.0      18
3.0      27
4.0      35
5.0     314
6.0     197
7.0     302
8.0     569
9.0     240
10.0    293
NaN       5
Name: count, dtype: int64

====================
Q159
Q159
1.0      14
2.0      25
3.0      32
4.0      62
5.0     291
6.0     198
7.0     321
8.0     515
9.0     252
10.0    297
NaN       5
Name: count, dtype: int64

====================
Q160
Q160
1.0     108
2.0      98
3.0     134
4.0     117
5.0     472
6.0     221
7.0     321
8.0     304
9.0     113
10.0    105
NaN      19
Name: count, dtype: int64

====================
Q161
Q161
1.0     119
2.0     108
3.0     163
4.0     109
5.0     542
6.0     260
7.0     272
8.0     248
9.0      85
10.0     83
NaN      23
Name: count, dtype: int64

====================
Q162
Q162
1.0     398
2.0     282
3.0     357
4.0     228
5.0     348
6.0     110
7.0     113
8.0      88
9.0      21
10.0     63
NaN       4
Name: count, dtype: int64

====================
Q163
Q163
1.0      37
2.0      44
3.0      91
4.0     104
5.0     343
6.0     250
7.0     367
8.0     418
9.0     178
10.0    171
NaN       9
Name: count, dtype: int64

====================
Q164
Q164
1.0     173
2.0      74
3.0     108
4.0      64
5.0     308
6.0     141
7.0     176
8.0     258
9.0     116
10.0    583
NaN      11
Name: count, dtype: int64

====================
Q277R
Q277R
1.0    1302
2.0     407
3.0     177
NaN     126
Name: count, dtype: int64

====================
Q278R
Q278R
1.0    1106
2.0     463
3.0     258
NaN     185
Name: count, dtype: int64

### 4.3 Assess Reverse Coding for Q27–Q32

Q27–Q32 are reviewed to determine whether reverse coding is required. Q28–Q31 are already coded such that higher scores indicate more egalitarian gender-role attitudes, so no reverse coding is necessary. Q27 measures the importance of making one's parents proud rather than gender-role attitudes and is therefore not included in the gender-role scale. Q32 concerns the perceived fulfilment of being a housewife compared with working for pay and has an ambiguous conceptual direction, so it is not reverse-coded at this stage.

### 4.4 Reverse-Code Negatively Worded Science and Technology Items (Q160 to Q162)

Q160–Q162 are negatively worded in relation to the intended science and technology attitude scale. The items are reverse-coded so that higher scores consistently represent more positive attitudes toward science and technology.

In [45]:
# Reverse-code Q160–Q162 so that the coding direction matches the intended interpretation
for col in ["Q160", "Q161", "Q162"]:
    df_clean[col] = df_clean[col].map(
        lambda x: 11 - x if pd.notna(x) else np.nan
    )

### 4.5 Check Q160–Q162 After Reverse Coding

The frequency distributions of Q160–Q162 are examined after reverse coding to verify that the response values have been recoded correctly and that higher scores consistently represent more positive attitudes toward science and technology.

In [46]:
# Display frequencies and percentages for Q160–Q162
for col in ["Q160", "Q161", "Q162"]:
    print("\n====================")
    print(col)

    counts = df_clean[col].value_counts(dropna=False).sort_index()
    percentages = (counts / 2012 * 100).round(2)

    output = pd.DataFrame({
        "Frequency": counts,
        "Percentage of Full Sample (%)": percentages
    })

    output.index = output.index.map(
        lambda x: "Missing" if pd.isna(x) else x
    )

    print(output)

====================
Q160
         Frequency  Percentage of Full Sample (%)
Q160
1.0            105                           5.22
2.0            113                           5.62
3.0            304                          15.11
4.0            321                          15.95
5.0            221                          10.98
6.0            472                          23.46
7.0            117                           5.82
8.0            134                           6.66
9.0             98                           4.87
10.0           108                           5.37
Missing         19                           0.94

====================
Q161
         Frequency  Percentage of Full Sample (%)
Q161
1.0             83                           4.13
2.0             85                           4.22
3.0            248                          12.33
4.0            272                          13.52
5.0            260                          12.92
6.0            542                          26.94
7.0            109                           5.42
8.0            163                           8.10
9.0            108                           5.37
10.0           119                           5.91
Missing         23                           1.14

====================
Q162
         Frequency  Percentage of Full Sample (%)
Q162
1.0             63                           3.13
2.0             21                           1.04
3.0             88                           4.37
4.0            113                           5.62
5.0            110                           5.47
6.0            348                          17.30
7.0            228                          11.33
8.0            357                          17.74
9.0            282                          14.02
10.0           398                          19.78
Missing          4                           0.20

### 4.6 Assess Parental Education Coding (Q277R and Q278R)

Q277R and Q278R measure the highest educational level attained by the respondent's mother and father, respectively. The variables are recoded into three education groups, where 1 represents lower education, 2 represents middle education, and 3 represents higher education. The variables are already coded in ascending order of educational attainment, so no reverse coding is required.

### 4.7 Final Variable Coding and Interpretation

The final coding of all selected variables is reviewed after missing-value recoding and reverse coding. The original question statements are provided alongside the final coding to document how each variable is interpreted in the analysis.

In [48]:
# Display the final coding, question wording, frequencies and percentages for all selected variables

variable_information = {
    "Q27": {
        "statement": "One of my main goals in life has been to make my parents proud.",
        "coding": "1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree."
    },
    "Q28": {
        "statement": "When a mother works for pay, the children suffer.",
        "coding": "1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian."
    },
    "Q29": {
        "statement": "On the whole, men make better political leaders than women do.",
        "coding": "1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian."
    },
    "Q30": {
        "statement": "A university education is more important for a boy than for a girl.",
        "coding": "1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian."
    },
    "Q31": {
        "statement": "On the whole, men make better business executives than women do.",
        "coding": "1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian."
    },
    "Q32": {
        "statement": "Being a housewife is just as fulfilling as working for pay.",
        "coding": "1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Direction is conceptually ambiguous; not reverse-coded."
    },
    "Q158": {
        "statement": "Science and technology are making our lives healthier, easier, and more comfortable.",
        "coding": "1 = Completely disagree; 10 = Completely agree. Higher scores = more positive attitudes toward science and technology."
    },
    "Q159": {
        "statement": "Because of science and technology, there will be more opportunities for the next generation.",
        "coding": "1 = Completely disagree; 10 = Completely agree. Higher scores = more positive attitudes toward science and technology."
    },
    "Q160": {
        "statement": "We depend too much on science and not enough on faith.",
        "coding": "Reverse-coded. Final scores range from 1–10, with higher scores = more positive attitudes toward science and technology."
    },
    "Q161": {
        "statement": "One of the bad effects of science is that it breaks down people's ideas of right and wrong.",
        "coding": "Reverse-coded. Final scores range from 1–10, with higher scores = more positive attitudes toward science and technology."
    },
    "Q162": {
        "statement": "It is not important for me to know about science in my daily life.",
        "coding": "Reverse-coded. Final scores range from 1–10, with higher scores = more positive attitudes toward science and technology."
    },
    "Q163": {
        "statement": "All things considered, would you say that the world is better off, or worse off, because of science and technology?",
        "coding": "1 = The world is a lot worse off; 10 = The world is a lot better off. Higher scores = more positive attitudes toward science and technology."
    },
    "Q164": {
        "statement": "How important is God in your life?",
        "coding": "1 = Not at all important; 10 = Very important. Higher scores = greater importance of God."
    },
    "Q277R": {
        "statement": "Highest educational level attained - Respondent's Mother (Recoded).",
        "coding": "1 = Lower education; 2 = Middle education; 3 = Higher education."
    },
    "Q278R": {
        "statement": "Highest educational level - Respondent's Father (Recoded).",
        "coding": "1 = Lower education; 2 = Middle education; 3 = Higher education."
    }
}

total_respondents = 2012

for col, info in variable_information.items():
    print("\n" + "=" * 90)
    print(col)
    print("Question:", info["statement"])
    print("Final coding:", info["coding"])
    print("\nFrequency and percentage of full sample (N = 2012):")

    counts = df_clean[col].value_counts(dropna=False).sort_index()
    percentages = (counts / total_respondents * 100).round(2)

    output = pd.DataFrame({
        "Frequency": counts,
        "Percentage of Full Sample (%)": percentages
    })

    output.index = output.index.map(
        lambda x: "Missing" if pd.isna(x) else x
    )

    print(output)

==========================================================================================
Q27
Question: One of my main goals in life has been to make my parents proud.
Final coding: 1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q27
1.0            576                          28.63
2.0           1148                          57.06
3.0            254                          12.62
4.0             23                           1.14
Missing         11                           0.55

==========================================================================================
Q28
Question: When a mother works for pay, the children suffer.
Final coding: 1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q28
1.0            104                           5.17
2.0            603                          29.97
3.0           1079                          53.63
4.0            218                          10.83
Missing          8                           0.40

==========================================================================================
Q29
Question: On the whole, men make better political leaders than women do.
Final coding: 1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q29
1.0             98                           4.87
2.0            514                          25.55
3.0           1086                          53.98
4.0            290                          14.41
Missing         24                           1.19

==========================================================================================
Q30
Question: A university education is more important for a boy than for a girl.
Final coding: 1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q30
1.0             57                           2.83
2.0            293                          14.56
3.0           1070                          53.18
4.0            585                          29.08
Missing          7                           0.35

==========================================================================================
Q31
Question: On the whole, men make better business executives than women do.
Final coding: 1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Higher scores = more egalitarian.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q31
1.0             45                           2.24
2.0            421                          20.92
3.0           1132                          56.26
4.0            401                          19.93
Missing         13                           0.65

==========================================================================================
Q32
Question: Being a housewife is just as fulfilling as working for pay.
Final coding: 1 = Strongly agree; 2 = Agree; 3 = Disagree; 4 = Strongly disagree. Direction is conceptually ambiguous; not reverse-coded.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q32
1.0            242                          12.03
2.0           1088                          54.08
3.0            555                          27.58
4.0            111                           5.52
Missing         16                           0.80

==========================================================================================
Q158
Question: Science and technology are making our lives healthier, easier, and more comfortable.
Final coding: 1 = Completely disagree; 10 = Completely agree. Higher scores = more positive attitudes toward science and technology.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q158
1.0             12                           0.60
2.0             18                           0.89
3.0             27                           1.34
4.0             35                           1.74
5.0            314                          15.61
6.0            197                           9.79
7.0            302                          15.01
8.0            569                          28.28
9.0            240                          11.93
10.0           293                          14.56
Missing          5                           0.25

==========================================================================================
Q159
Question: Because of science and technology, there will be more opportunities for the next generation.
Final coding: 1 = Completely disagree; 10 = Completely agree. Higher scores = more positive attitudes toward science and technology.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q159
1.0             14                           0.70
2.0             25                           1.24
3.0             32                           1.59
4.0             62                           3.08
5.0            291                          14.46
6.0            198                           9.84
7.0            321                          15.95
8.0            515                          25.60
9.0            252                          12.52
10.0           297                          14.76
Missing          5                           0.25

==========================================================================================
Q160
Question: We depend too much on science and not enough on faith.
Final coding: Reverse-coded. Final scores range from 1–10, with higher scores = more positive attitudes toward science and technology.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q160
1.0            105                           5.22
2.0            113                           5.62
3.0            304                          15.11
4.0            321                          15.95
5.0            221                          10.98
6.0            472                          23.46
7.0            117                           5.82
8.0            134                           6.66
9.0             98                           4.87
10.0           108                           5.37
Missing         19                           0.94

==========================================================================================
Q161
Question: One of the bad effects of science is that it breaks down people's ideas of right and wrong.
Final coding: Reverse-coded. Final scores range from 1–10, with higher scores = more positive attitudes toward science and technology.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q161
1.0             83                           4.13
2.0             85                           4.22
3.0            248                          12.33
4.0            272                          13.52
5.0            260                          12.92
6.0            542                          26.94
7.0            109                           5.42
8.0            163                           8.10
9.0            108                           5.37
10.0           119                           5.91
Missing         23                           1.14

==========================================================================================
Q162
Question: It is not important for me to know about science in my daily life.
Final coding: Reverse-coded. Final scores range from 1–10, with higher scores = more positive attitudes toward science and technology.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q162
1.0             63                           3.13
2.0             21                           1.04
3.0             88                           4.37
4.0            113                           5.62
5.0            110                           5.47
6.0            348                          17.30
7.0            228                          11.33
8.0            357                          17.74
9.0            282                          14.02
10.0           398                          19.78
Missing          4                           0.20

==========================================================================================
Q163
Question: All things considered, would you say that the world is better off, or worse off, because of science and technology?
Final coding: 1 = The world is a lot worse off; 10 = The world is a lot better off. Higher scores = more positive attitudes toward science and technology.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q163
1.0             37                           1.84
2.0             44                           2.19
3.0             91                           4.52
4.0            104                           5.17
5.0            343                          17.05
6.0            250                          12.43
7.0            367                          18.24
8.0            418                          20.78
9.0            178                           8.85
10.0           171                           8.50
Missing          9                           0.45

==========================================================================================
Q164
Question: How important is God in your life?
Final coding: 1 = Not at all important; 10 = Very important. Higher scores = greater importance of God.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q164
1.0            173                           8.60
2.0             74                           3.68
3.0            108                           5.37
4.0             64                           3.18
5.0            308                          15.31
6.0            141                           7.01
7.0            176                           8.75
8.0            258                          12.82
9.0            116                           5.77
10.0           583                          28.98
Missing         11                           0.55

==========================================================================================
Q277R
Question: Highest educational level attained - Respondent's Mother (Recoded).
Final coding: 1 = Lower education; 2 = Middle education; 3 = Higher education.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q277R
1.0           1302                          64.71
2.0            407                          20.23
3.0            177                           8.80
Missing        126                           6.26

==========================================================================================
Q278R
Question: Highest educational level - Respondent's Father (Recoded).
Final coding: 1 = Lower education; 2 = Middle education; 3 = Higher education.

Frequency and percentage of full sample (N = 2012):
         Frequency  Percentage of Full Sample (%)
Q278R
1.0           1106                          54.97
2.0            463                          23.01
3.0            258                          12.82
Missing        185                           9.19